console.log("Hello World")
var english = ["Species", "Career", "Specializations", "Threshold", "Current", "Melee", "Soak", "Wounds", "Strain", "Defense", "Brawn", "Agility", "Intellect", "Cunning", "Willpower", "Presence", "Rank", "Roll", "Adj.", "Available XP", "Total XP", "Encumbrance", "Weapons", "Armor","Personal Gear", "Assets", "Resources", "Critical Injuries", "Conditions", "Astrogation", "Athletics", "Charm", "Coercion", "Computers", "Cool", "Coordination", "Deception", "Discipline", "Leadership", "Mechanics", "Medicine", "Negotiation", "Perception", "Piloting: Planetary", "Piloting: Space", "Resilience", "Skulduggery", "Stealth", "Streetwise", "Survival", "Vigilance", "Brawl", "Gunnery", "Lightsaber", "Melee", "Ranged: Light", "Ranged: Heavy", "Knowledge: Core Worlds", "Knowledge: Education", "Knowledge: Lore", "Knowledge: Outer Rim", "Knowledge: Underworld", "Knowledge: Warfare", "Knowledge: Xenology", "Background", "Morality", "Motivation", "Description", "Other Notes", "Private Notes", "\\(Br\\)", "\\(Ag\\)", "\\(Int\\)", "\\(Cun\\)", "\\(Will\\)", "\\(Pr\\)", "Ranged", "Skill"]
var deutsch = ["Spezies", "Beruf", "Spezialisierung", "Limit", "Aktuell", "Nahkampf", "Absorption", "Wunden", "Erschöpfung", "Verteidigung", "Stärke", "Gewandheit", "Intelligenz", "List", "Willenkraft", "Charisma", "Rang", "Würfel", "Zusatz", "Verfügbare XP", "Ausgegebene XP", "Belastung", "Waffen", "Rüstung", "Persöhnliche Ausrüstung", "Vermögen", "Ressourcen", "Kritische Verletzungen", "Zustände", "Astronavigation","Athletik", "Charme", "Einschüchterung", "Computertechnik", "Coolness", "Koordination", "Täuschung", "Disziplin", "Führungsqualität", "Mechanik", "Medizin", "Verhandeln", "Wahrnehmung", "Pilot (Planetar)", "Pilot (Weltraum)", "Widerstandskraft", "Infiltration", "Heimlichkeit", "Straßenwissen", "Überlewen", "Wachsamkeit", "Handgemenge", "Schießerei", "Lichtschwert", "Nahkampf", "Leichte Fernkampfwaffen", "Schwere Fernkampfwaffen", "Wissen: Kernwelten", "Wissen: Allgemeinbildung", "Wissen: Altes Wissen", "Wissen: Äußerer Rand", "Wissen: Unterwelten", "Wissen: Kriegsführung", "Wissen: Xenologie", "HINTERGRUND", "MORAL", "MOTIVATION", "BESCHREIBUNG", "ANDERE NOTIZEN", "PRIVATE NOTIZEN","(St)", "(Ge)", "(In)", "(Li)", "(Wi)", "(Ch)", "Fernkampf", "Fertigkeiten"];

console.log(english.length);
console.log(deutsch.length);

var i;
for (i = 0; i < english.length; i++){
  document.body.innerHTML = document.body.innerHTML.replace(new RegExp(english[i], "g"), deutsch[i]);
}